{{- if and .Values.server.enabled .Values.server.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "patchmon.server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patchmon.server.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.server.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.server.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "patchmon.server.selectorLabels" . | nindent 6 }}
{{- end }}
